server:
  port: 18080
  servlet:
    context-path: /
  compression:
    enabled: true

spring:
  application:
    name: gbtmedia
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:h2:file:/var/gbtmedia/h2/db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false

logging:
  file:
    path: /var/gbtmedia/log
  level:
    cn.gbtmedia: debug
