version: '3'
services:
  gbtmedia:
    image: xqs2018/gbtmedia
    container_name: gbtmedia
    restart: always
    network_mode: host
    environment:
      TZ: Asia/Shanghai
      #server-config.ip: 192.168.2.87
      #server-config.accessIp: 192.168.2.87
      #server-config.publicIp: 192.168.2.87
    volumes:
      - ./mount/gbt28181:/var/gbtmedia/gbt28181
      - ./mount/jtt808:/var/gbtmedia/jtt808
      - ./mount/h2:/var/gbtmedia/h2
      - ./mount/log:/var/gbtmedia/log
